# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-10-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Company Name *')),
                ('email', models.EmailField(max_length=254, verbose_name=b'Email *')),
                ('description', models.TextField(blank=True, help_text=b'Feel free to leave it for now, we will get access to know your company', null=True, verbose_name=b'Job Description / Position Link')),
                ('position', models.CharField(choices=[(b'fulltime', b'full time'), (b'more20', b'more than 20 hours/week'), (b'less20', b'less than 20 hours/week')], max_length=32, verbose_name=b'Position *')),
                ('application_date', models.DateTimeField(auto_now=True, verbose_name=b'Basvuru Tarihi')),
            ],
            options={
                'verbose_name': 'Sirket',
                'verbose_name_plural': 'Sirketler listesi',
            },
        ),
        migrations.CreateModel(
            name='Developers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Developer Adi')),
                ('email', models.EmailField(max_length=254, verbose_name=b'email')),
                ('country', models.CharField(max_length=64, verbose_name=b'Ulke Adi')),
                ('english_level', models.CharField(choices=[(b'advanced', b'advanced'), (b'good', b'good'), (b'intermediate', b'intermediate'), (b'elementary', b'elementary'), (b'beginner', b'beginner')], max_length=64, verbose_name=b'Ingilizce seviyesi')),
                ('specialization', models.CharField(choices=[(b'backend', b'backend developer'), (b'frontend', b'frontend'), (b'fullstack', b'fullstack'), (b'software', b'software engineer'), (b'datascientist', b'datascientist'), (b'dataengineer', b'dataengineer'), (b'dataanalyst', b'dataanalyst'), (b'devops', b'devops'), (b'gamedesigner', b'gamedesigner'), (b'designer', b'designer'), (b'qa', b'qa'), (b'other', b'other')], max_length=64, verbose_name=b'Posizyon')),
                ('description', models.TextField(blank=True, null=True, verbose_name=b'aciklama')),
                ('experience', models.CharField(choices=[(b'1', b'1'), (b'2', b'2'), (b'3', b'3'), (b'4', b'4'), (b'5-7', b'5-7'), (b'7-10', b'7-10'), (b'10+', b'10+')], max_length=64, verbose_name=b'tecrube')),
                ('cv', models.FileField(blank=True, null=True, upload_to=b'', verbose_name=b'cv')),
                ('application_date', models.DateTimeField(auto_now=True, verbose_name=b'Basvuru Tarihi')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developer listesi',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'skills')),
            ],
        ),
        migrations.AddField(
            model_name='developers',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='developer', to='app.Skills', verbose_name=b'Maharetler'),
        ),
    ]
